<div id="book-bed">
    <label class="book-title-type">Loại xe giường nằm</label>
    <div class="boot-seat-floor">
        <label>Tầng 1</label>
        <table class="book-seat">
            <?php
            $index = 1;

            for ($i = 0; $i < 5; $i++) {

                echo '<tr>';

                $k = 0;
                for ($j = 0; $j < 5; $j++) {
                    if ($j % 2 == 0) {
                        echo "<td id='seat-bed-$index'>$index</td>";
                        $index++;
                    } else {
                        echo '<td></td>';
                    }
                }
            }

            echo '</tr>';
            ?>
        </table>
    </div>
    <div class="boot-seat-floor">
        <label>Tầng 2</label>
        <table class="book-seat">
            <?php
            for ($i = 0; $i < 5; $i++) {

                echo '<tr>';

                $k = 0;
                for ($j = 0; $j < 5; $j++) {
                    if ($j % 2 == 0) {
                        echo "<td id='seat-bed-$index'>$index</td>";
                        $index++;
                    } else {
                        echo '<td></td>';
                    }
                }
            }

            echo '</tr>';
            ?>
        </table>
    </div>
    <div>
        <ul class="book-seat-information">
            <li>
                <span>Tổng số ghế: </span>30
            </li>
            <li>
                <span>Số ghế trống: </span><span class="count-available-seat"></span>
            </li>
        </ul>
    </div>
</div>