<div id="step-2" hidden ng-controller="BookTicketController">
    <div class="row panel-info">
        <div class="col-md-4 center">
            <img src="/img/Operators/HoangLong.png" id="result-logo" class="logo" alt="Logo" />
        </div>
        <div class="col-md-4">
            <h5><small>Hãng xe: </small><span id="result-operator"></span></h5>
            <h5><small>Ngày đi: </small><span id="result-date"></span></h5>
        </div>
        <div class="col-md-4">
            <h5><small>Nơi đi: </small><span id="result-from"></span></h5>
            <h5><small>Nơi đến: </small><span id="result-to"></span></h5>
            <h5><small>Giá vé: </small><span id="result-price"></span></h5>
        </div>
    </div>
    <div class="row">
        <div class="col-md-5">
            <fieldset>
                <legend>Sơ đồ vị trí</legend>
                <?php include __DIR__ . '/../express/book-seat.phtml' ?>
                <?php include __DIR__ . '/../express/book-bed.phtml' ?>
            </fieldset>
        </div>
        <div class="col-md-7">
            <fieldset>
                <legend class="book-information">Thông tin khách hàng</legend>
                <ul class="book-customer-information">
                    <li>Tên khách hàng (<abbr title="Bắt buộc">*</abbr>)</li>
                    <li id="book-name">
                        <input type="text" class="form-control" ng-model="customer" spellcheck="false" required="Tên khách hàng không được bỏ trống" />
                    </li>
                    <li>Điện thoại (<abbr title="Bắt buộc">*</abbr>)</li>
                    <li id="book-phone">
                        <input type="text" class="form-control" ng-model="phone" spellcheck="false" required="Số điện thoại không được bỏ trống" />
                    </li>
                    <li>Email (<abbr title="Bắt buộc">*</abbr>)</li>
                    <li id="book-email">
                        <input type="email" class="form-control" ng-model="email" spellcheck="false" required="Email không được bỏ trống" />
                    </li>
                    <li>Danh sách vé (<abbr title="Bắt buộc">*</abbr>)</li>
                    <li id="book-tickets">
                        <input type="text" id="list-seats" data-role="tagsinput" />
                    </li>
                </ul>
            </fieldset>
            <ul class="book-buttons">
                <li>
                    <button type="button" class="btn btn-default" ng-click="back()">Hủy</button>
                </li>
                <li class="btn-book-ticket-bound">
                    <button type="button" class="btn btn-primary" ng-click="pay()">
                        <span class="glyphicon glyphicon-credit-card icon-credit-card"></span>Thanh toán
                    </button>
                </li>
            </ul>
        </div>
    </div>
</div>

<div class="modal fade" id="error-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">Thông báo</h4>
            </div>
            <div class="modal-body">
                <h5 id="error-content"></h5>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">OK</button>
            </div>
        </div>
    </div>
</div>