<div id="book-seat">
    <label class="book-title-type">Loại xe ghế ngồi</label>
    <table class="book-seat">
        <?php
        $index = 1;

        for ($i = 0; $i < 10; $i++) {

            echo '<tr>';

            for ($j = 0; $j < 5; $j++) {
                if ($j === 2) {
                    echo '<td></td>';
                } else {
                    echo "<td id='seat-$index'>$index</td>";
                    $index++;
                }
            }
        }

        echo '</tr>';
        ?>
    </table>
    <div>
        <ul class="book-seat-information">
            <li>
                <span>Tổng số ghế: </span> 40
            </li>
            <li>
                <span>Số ghế trống: </span><span class="count-available-seat"></span>
            </li>
        </ul>
    </div>
</div>