<div id="step-2" hidden ng-controller="BookTicketController">
    <div class="row panel-info">
        <div class="col-md-4 center">
            <img src="/img/Operators/HoangLong.png" class="result-logo logo" alt="Logo" />
        </div>
        <div class="col-md-4">
            <h5><small>Hãng xe: </small><span class="result-operator"></span></h5>
            <h5><small>Ngày đi: </small><span class="result-date"></span></h5>
        </div>
        <div class="col-md-4">
            <h5><small>Nơi đi: </small><span class="result-from"></span></h5>
            <h5><small>Nơi đến: </small><span class="result-to"></span></h5>
            <h5><small>Giá vé: </small><span class="result-price"></span></h5>
            <input type="hidden" id="price-ticket" />
        </div>
    </div>
    <div class="row">
        <div class="col-md-5">
            <fieldset>
                <legend>Sơ đồ vị trí</legend>
                <?php include __DIR__ . '/../express/book-seat.phtml' ?>
                <?php include __DIR__ . '/../express/book-bed.phtml' ?>
            </fieldset>
        </div>
        <div class="col-md-7">
            <div id="customer-information" class="hidden-panel">
                <fieldset>
                    <legend class="book-information">Thông tin khách hàng</legend>
                    <ul class="book-customer-information">
                        <li>Danh sách vé (<abbr title="Bắt buộc">*</abbr>)</li>
                        <li id="book-tickets">
                            <input type="text" id="list-seats" data-role="tagsinput" />
                        </li>
                    </ul>
                </fieldset>
                <ul class="book-buttons">
                    <li>
                        <button type="button" class="btn btn-default" ng-click="back()">Hủy</button>
                    </li>
                    <li class="btn-book-ticket-bound">
                        <button type="button" class="btn btn-primary" ng-click="pay()">
                            <span class="glyphicon glyphicon-credit-card icon-credit-card"></span>Thanh toán
                        </button>
                    </li>
                </ul>
            </div>
            <div id="customer-required" class="hidden-panel">
                <div>
                    <h5>Bạn vui lòng Đăng Nhập hoặc Đăng Ký để có thể đặt vé</h5>
                    <button type="button" class="btn btn-primary" ng-click="accept()">Xác nhận</button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="error-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">Thông báo</h4>
            </div>
            <div class="modal-body">
                <h5 id="error-content"></h5>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">OK</button>
            </div>
        </div>
    </div>
</div>