<div id="step-3" hidden ng-controller="paymentController">
    <div>
        <div class="center-screen payment-panel">
            <div>
                <div class="col-md-7">
                    <div class="col-md-4">
                        <ul class="payment-list-credit-card-title">
                            <li>Mã thẻ</li>
                            <li>Loại thẻ</li>
                        </ul>
                    </div>
                    <div class="col-md-8">
                        <ul class="payment-list-credit-card-form">
                            <li>
                                <input type="text" class="form-control"/>
                            </li>
                            <li>
                                <select class="combobox">
                                    <option value="VISA">VISA</option>
                                    <option value="MASTER">MASTER CARD</option>
                                    <option value="DISCOVER">DISCOVER</option>
                                    <option value="AMERICAN">AMERICAN EXPRESS</option>
                                </select>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-5">
                    <ul class="payment-total">
                        <li>Tổng tiền:</li>
                        <li>1.900.000 VND</li>
                    </ul>
                    <div class="right">
                        <button class="btn btn-default">Hủy</button>
                        <button class="btn btn-primary"><span class="glyphicon glyphicon-credit-card icon-credit-card"></span>Thanh toán</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <table class="table list-tickets">
        <thead>
        <th>#</th>
        <th>Mã vé</th>
        <th>Giá tiền</th>
        <th>--</th>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>