<div id="step-3" hidden ng-controller="paymentController">
    <div>
        <div class="row panel-info">
            <div class="col-md-4 center">
                <img src="/img/logo-icon.png" class="result-logo logo" alt="Logo" />
            </div>
            <div class="col-md-4">
                <h5><small>Hãng xe: </small><span class="result-operator"></span></h5>
                <h5><small>Ngày đi: </small><span class="result-date"></span></h5>
            </div>
            <div class="col-md-4">
                <h5><small>Nơi đi: </small><span class="result-from"></span></h5>
                <h5><small>Nơi đến: </small><span class="result-to"></span></h5>
            </div>
        </div>
        <div class="center-screen payment-panel">
            <div>
                <div class="col-md-7">
                    <div class="col-md-4">
                        <ul class="payment-list-credit-card-title">
                            <li>Mã thẻ</li>
                            <li>Loại thẻ</li>
                        </ul>
                    </div>
                    <div class="col-md-8">
                        <ul class="payment-list-credit-card-form">
                            <li>
                                <input type="text" class="form-control" ng-model="creditCard" id="credit-card-id" />
                            </li>
                            <li id="credit-card">
                                <select class="combobox" id="credit-card-type">
                                    <option value="VISA">VISA</option>
                                    <option value="MASTER">MASTER CARD</option>
                                    <option value="DISCOVER">DISCOVER</option>
                                    <option value="AMERICAN">AMERICAN EXPRESS</option>
                                </select>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-5">
                    <ul class="payment-total">
                        <li>Tổng tiền:</li>
                        <li id="total-price">1.900.000 VND</li>
                    </ul>
                    <div class="right">
                        <button type="button" class="btn btn-default" data-toggle="modal" data-target="#cancel-modal">Hủy</button>
                        <button type="button" class="btn btn-primary" ng-click="pay()">
                            <span class="glyphicon glyphicon-credit-card icon-credit-card"></span>Thanh toán
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <table class="table table-bordered table-hover list-tickets">
        <thead>
            <th class="center">#</th>
            <th class="center">Mã vé</th>
            <th class="center">Ghế</th>
            <th class="center">--</th>
        </thead>
        <tbody id="unpaid-tickets">
        </tbody>
    </table>
    <div class="modal fade" id="payment-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="myModalLabel">Thông báo</h4>
                </div>
                <div class="modal-body">
                    <h5 id="message-content"></h5>
                    <h5 id="error-content"></h5>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" ng-click="paySuccess()" data-dismiss="modal">OK</button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="cancel-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="myModalLabel">Thông báo</h4>
                </div>
                <div class="modal-body">
                    Bạn có chắc muốn hủy toàn bộ vé chứ?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Hủy</button>
                    <button type="button" class="btn btn-warning" ng-click="cancel()" data-dismiss="modal">Đồng ý</button>
                </div>
            </div>
        </div>
    </div>
</div>