<div id="step-3" hidden ng-controller="paymentController">
    <div>
        <div class="row panel-info">
            <div class="col-md-4 center">
                <img src="/img/Operators/HoangLong.png" class="result-logo logo" alt="Logo" />
            </div>
            <div class="col-md-4">
                <h5><small>Hãng xe: </small><span class="result-operator"></span></h5>
                <h5><small>Ngày đi: </small><span class="result-date"></span></h5>
            </div>
            <div class="col-md-4">
                <h5><small>Nơi đi: </small><span class="result-from"></span></h5>
                <h5><small>Nơi đến: </small><span class="result-to"></span></h5>
            </div>
        </div>
        <div class="center-screen payment-panel">
            <div>
                <div class="col-md-7">
                    <div class="col-md-4">
                        <ul class="payment-list-credit-card-title">
                            <li>Mã thẻ</li>
                            <li>Loại thẻ</li>
                        </ul>
                    </div>
                    <div class="col-md-8">
                        <ul class="payment-list-credit-card-form">
                            <li>
                                <input type="text" class="form-control"/>
                            </li>
                            <li>
                                <select class="combobox">
                                    <option value="VISA">VISA</option>
                                    <option value="MASTER">MASTER CARD</option>
                                    <option value="DISCOVER">DISCOVER</option>
                                    <option value="AMERICAN">AMERICAN EXPRESS</option>
                                </select>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-5">
                    <ul class="payment-total">
                        <li>Tổng tiền:</li>
                        <li id="total-price">1.900.000 VND</li>
                    </ul>
                    <div class="right">
                        <button type="button" class="btn btn-default" ng-click="back()">Hủy</button>
                        <button type="button" class="btn btn-primary" ng-click="pay()">
                            <span class="glyphicon glyphicon-credit-card icon-credit-card"></span>Thanh toán
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <table class="table table-bordered table-hover list-tickets">
        <thead>
            <th class="center">#</th>
            <th class="center">Mã vé</th>
            <th class="center">Ghế</th>
            <th class="center">--</th>
        </thead>
        <tbody id="unpaid-tickets">
        </tbody>
    </table>
</div>