<?php include __DIR__ . '/../express/search-form.phtml' ?>

<div class="app-standard center-screen book-panel">
    <div class="col-md-2 search-information-trip">
        <div class="search-information-trip-panel">
            <div class="search-information-content-layout">
                <ul class="search-information-content">
                    <li>
                        <h4 id="from"><?php echo $from[0] ?></h4>
                    </li>
                    <li class="glyphicon glyphicon-chevron-down">
                    </li>
                    <li>
                        <h4 id="to"><?php echo $to[0] ?></h4>
                    </li>
                    <li class="search-information-time">
                        <span class="glyphicon glyphicon-time icon-time"></span>
                        <h5 id="date"><?php echo $date ?></h5>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-10">
        <ol class="breadcrumb">
            <li id="book-step-1" class="badge search-step-active">Hành trình</li>
            <li id="book-step-2">Chọn chỗ</li>
            <li id="book-step-3">Thanh toán</li>
        </ol>
        <div id="trip-book-content">
            <input type="hidden" id="car-id" />
            <input type="hidden" id="route-id" />
            <?php include __DIR__ . '/../express/search-result.phtml' ?>
            <?php include __DIR__ . '/../express/book.phtml' ?>
            <?php include __DIR__ . '/../express/payment.phtml' ?>
        </div>
    </div>
</div>