<div class="app-standard center-screen">
    <div class="search-form-panel" ng-controller="SearchBarController">
        <ul class="search-form-components">
            <li class="search-form-form">
                <select class="combobox" id="search-from">
                    <?php foreach ($provinces as $province) : ?>
                        <option value="<?php echo $province['MaTinh'] ?>"><?php echo $province['TenTinh'] ?></option>
                    <?php endforeach ?>
                </select>
            </li>
            <li class="search-form-form">
                <select class="combobox" id="search-to">
                    <?php foreach ($provinces as $province) : ?>
                        <option value="<?php echo $province['MaTinh'] ?>"><?php echo $province['TenTinh'] ?></option>
                    <?php endforeach ?>
                </select>
            </li>
            <li class="search-form-form">
                <div class="form-group">
                    <div class="input-group date" id="datetimepicker">
                        <input type="text" class="form-control" id="search-date" data-date-format="DD/MM/YYYY"/>
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                </div>
            </li>
            <li>
                <button type="button" class="btn btn-success" ng-click="submit()"><span class="glyphicon glyphicon-search"></span></button>
            </li>
        </ul>
    </div>
</div>