<div class="main-contain">
    <div class="management-operator center-screen">
        <form action="#">
            <ul>
                <li class="management-operator-title">Tên hãng xe</li>
                <li>
                    <input type="text" class="form-control"/>
                </li>
                <li class="management-operator-title">Logo</li>
                <li>
                    <input id="input-id" type="file" class="file" data-preview-file-type="text" >
                </li>
                <li class="management-operator-button">
                    <button type="button" class="btn btn-primary">Hoàn tất</button>
                </li>
            </ul>
        </form>
    </div>
</div>