<div class="main-contain hidden">
    <div class="schedule-contain center-screen">
        <div class="col-md-6">
            <h5>Từ khóa</h5>
            <input type="text" class="form-control" autocomplete="off"/>
        </div>
        <div class="col-md-3">
            <h5>Tiêu chí</h5>
            <div class="dropdown">
                <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
                    Tìm kiếm
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Ngày đi</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Giờ đi</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Nơi đi</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Nơi đến</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Giá vé</a></li>
                </ul>
            </div>
        </div>
        <div class="col-md-3 distance-buttons">
            <button type="button" class="btn btn-info"><span class="glyphicon glyphicon-plus"></span>Thêm</button>
        </div>
    </div>
    <div class="table-responsive table-space">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>Mã số</th>
                <th>Ngày đi</th>
                <th>Giờ đi</th>
                <th>Nơi đi</th>
                <th>Nơi đến</th>
                <th>Giá vé</th>
                <th>#</th> <!-- Remove Column -->
                <th>#</th> <!-- Edit Column -->
            </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
    <nav class="center" ">
        <ul class="pagination">
            <li><a href="#">&laquo;</a></li>
            <li><a href="#">1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><a href="#">5</a></li>
            <li><a href="#">&raquo;</a></li>
        </ul>
    </nav>
</div>