<div class="main-contain hidden">
    <div class="distance-contain center-screen">
        <div class="col-md-4">
            <h5>Điểm khởi hành</h5>
            <input type="text" class="form-control"/>
        </div>
        <div class="col-md-4">
            <h5>Điểm kết thúc</h5>
            <input type="text" class="form-control"/>
        </div>
        <div class="col-md-4 distance-buttons">
            <button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-search"></span>Tìm kiếm</button>
            <button type="button" class="btn btn-info"><span class="glyphicon glyphicon-plus"></span>Thêm</button>
        </div>
    </div>
    <div class="table-responsive table-space">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Mã số</th>
                    <th>Điểm khởi hành</th>
                    <th>Điểm kết thúc</th>
                    <th>Giá vé</th>
                    <th>#</th> <!-- Remove Column -->
                    <th>#</th> <!-- Edit Column -->
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
    <nav class="center">
        <ul class="pagination">
            <li><a href="#">&laquo;</a></li>
            <li><a href="#">1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><a href="#">5</a></li>
            <li><a href="#">&raquo;</a></li>
        </ul>
    </nav>
</div>