<div ng-controller="LoginController">
    <div class="backend-login">
        <div class="center-screen">
            <div class="page-header center">
                <h1>Vé Xe Của Tui <small> - Công ty TNHH Sao Mai</small></h1>
            </div>
        </div>
        <div class="backend-login-panel center-screen">
            <div class="col-md-4 backend-login-avatar">
                <img src="<?php echo $this->basePath() ?>/img/logo-icon.png" class="backend-icon" alt="Administrator"/>
            </div>
            <div class="col-md-8">
                <div>
                    <ul class="center-screen backend-login-form">
                        <li>
                            <input type="text" name="admin_login_user" ng-model="admin_login_user" class="form-control" autocomplete="off" ng-enter="login()" placeholder="Tên đăng nhập" />
                        </li>
                        <li>
                            <input type="password" ng-model="admin_login_password" class="form-control" autocomplete="off" ng-enter="login()" placeholder="Mật khẩu" />
                        </li>
                        <li class="center">
                            <button type="button" class="btn btn-primary" ng-click="login()" id="btn-submit" data-loading-text="Loading...">Đăng nhập</button>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="myModalLabel">Thông báo</h4>
                </div>
                <div class="modal-body">
                    <h5>{{message_error}}</h5>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">OK</button>
                </div>
            </div>
        </div>
    </div>
</div>