<div class="app-standard center-screen book-panel">
    <div class="col-md-2 search-information-trip">
        <div class="search-information-trip-panel">
            <div class="search-information-content-layout">
                <ul class="search-information-content">
                    <li>
                        <h4>Tp.Hồ Chí Minh</h4>
                    </li>
                    <li class="glyphicon glyphicon-chevron-down">
                    </li>
                    <li>
                        <h4>Tp.Cần Thơ</h4>
                    </li>
                    <li class="search-information-time">
                        <span class="glyphicon glyphicon-time icon-time"></span><h5>01/11/2014</h5>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-10">
        <ol class="breadcrumb">
            <li class="badge search-step-active">Hành trình</li>
            <li>Chọn chỗ</li>
            <li>Thanh toán</li>
        </ol>
        <div id="trip-book-content">
            <div id="step-1" hidden>
                <table class="table">
                    <thead>
                    <tr>
                        <th>Hãng xe</th>
                        <th>Nơi đi</th>
                        <th>Nơi đến</th>
                        <th>Giờ đi</th>
                        <th>Loại xe</th>
                        <th>Giá vé</th>
                        <th></th> <!-- Nút Đặt vé -->
                    </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
            <?php include __DIR__ . '/../trip/book.phtml'  ?>
            <?php include __DIR__ . '/../trip/payment.phtml'  ?>
        </div>
    </div>
</div>