<div class="app-standard center-screen">
    <div class="search-form-panel">
        <ul class="search-form-components">
            <li class="search-form-form">
                <select class="combobox">
                    <option value="PA">Pennsylvania</option>
                    <option value="CT">Connecticut</option>
                    <option value="NY">New York</option>
                    <option value="MD">Maryland</option>
                    <option value="VA">Virginia</option>
                </select>
            </li>
            <li class="search-form-form">
                <select class="combobox">
                    <option value="PA">Pennsylvania</option>
                    <option value="CT">Connecticut</option>
                    <option value="NY">New York</option>
                    <option value="MD">Maryland</option>
                    <option value="VA">Virginia</option>
                </select>
            </li>
            <li class="search-form-form">
                <div class="form-group">
                    <div class="input-group date" id="datetimepicker">
                        <input type="text" class="form-control" data-date-format="DD/MM/YYYY"/>
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                </div>
            </li>
            <li>
                <button class="btn btn-success"><span class="glyphicon glyphicon-search"></span></button>
            </li>
        </ul>
    </div>
</div>