<div>
    <img src="<?php echo $this->basePath() ?>/img/cover.jpg" alt="Cover" class="cover-image"/>
    <div class="cover-advertisment">
        <div class="app-standard center-screen cover-logos">
            <img src="<?php echo $this->basePath() ?>/img/Operators/HoangLong.png" alt="Hoàng Long"/>
            <img src="<?php echo $this->basePath() ?>/img/Operators/MaiLinhExpress.jpg" alt="Mai Linh Express"/>
            <img src="<?php echo $this->basePath() ?>/img/Operators/PhuongTrang.jpg" alt="Phương Trang"/>
            <img src="<?php echo $this->basePath() ?>/img/Operators/ThanhBuoi.jpg" alt="Thanh Bưởi"/>
        </div>
    </div>
</div>