<div>
    <img src="/img/cover.jpg" alt="Cover" class="cover-image" />
    <div class="pnl-book-ticket" ng-controller="bookTicketController">
        <div>
            <div class="col-md-3">
                <h5>Nơi đi</h5>
                <select class="combobox" id="location-start">
                    <?php foreach ($provinces as $province) : ?>
                        <option value="<?php echo $province['MaTinh'] ?>"><?php echo trim($province['TenTinh']) ?></option>
                    <?php endforeach ?>
                </select>
            </div>
            <div class="col-md-3">
                <h5>Nơi đến</h5>
                <select class="combobox" id="location-end">
                    <?php foreach ($provinces as $province) : ?>
                        <option value="<?php echo $province['MaTinh'] ?>"><?php echo trim($province['TenTinh']) ?></option>
                    <?php endforeach ?>
                </select>
            </div>
            <div class="col-md-3">
                <h5>Thời gian</h5>
                <div class="form-group">
                    <div class='input-group date' id='datetimepicker'>
                        <input type='text' class="form-control" id="date" data-date-format="DD/MM/YYYY" />
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <button class="btn btn-success btn-search" ng-click="submit()">Tìm kiếm</button>
            </div>
        </div>

    </div>
</div>