<div class="index-content">
    <div class="app-standard center-screen">
        <div class="center-screen index-book-panel">
            <div>
                <ul class="index-book-components">
                    <li>
                        <h2>Mua Vé Ngay</h2>
                    </li>
                    <li class="index-book-title">Nơi đi</li>
                    <li>
                        <select class="combobox">
                            <option value="PA">Pennsylvania</option>
                            <option value="CT">Connecticut</option>
                            <option value="NY">New York</option>
                            <option value="MD">Maryland</option>
                            <option value="VA">Virginia</option>
                        </select>
                    </li>
                    <li class="index-book-title">Nơi đến</li>
                    <li>
                        <select class="combobox">
                            <option value="PA">Pennsylvania</option>
                            <option value="CT">Connecticut</option>
                            <option value="NY">New York</option>
                            <option value="MD">Maryland</option>
                            <option value="VA">Virginia</option>
                        </select>
                    </li>
                    <li class="index-book-title">Ngày đi</li>
                    <li>
                        <div class="form-group">
                            <div class="input-group date" id="datetimepicker">
                                <input type="text" class="form-control" data-date-format="DD/MM/YYYY"/>
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                        </div>
                    </li>
                    <li>
                        <button class="btn btn-success btn-book-ticket">Tìm chuyến</button>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>