<div>
    <img src="/img/cover.jpg" alt="Cover" class="cover-image" />
    <div class="pnl-book-ticket">
        <div>
            <div class="col-md-3">
                <h5>Nơi đi</h5>
                <select class="combobox">
                    <option value="PA">Pennsylvania</option>
                    <option value="CT">Connecticut</option>
                    <option value="NY">New York</option>
                    <option value="MD">Maryland</option>
                    <option value="VA">Virginia</option>
                </select>
            </div>
            <div class="col-md-3">
                <h5>Nơi đến</h5>
                <select class="combobox">
                    <option value="PA">Pennsylvania</option>
                    <option value="CT">Connecticut</option>
                    <option value="NY">New York</option>
                    <option value="MD">Maryland</option>
                    <option value="VA">Virginia</option>
                </select>
            </div>
            <div class="col-md-3">
                <h5>Thời gian</h5>
                <div class="form-group">
                    <div class='input-group date' id='datetimepicker'>
                        <input type='text' class="form-control" data-date-format="DD/MM/YYYY" />
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <button class="btn btn-success btn-search">Tìm kiếm</button>
            </div>
        </div>

    </div>
</div>