<div class="main-contain" ng-controller="addManagerController as AddManagerCtrl">
    <div class="center-screen profile-panel admin-panel">
        <form action="/admin/manager/add" method="post">
            <ul>
                <li class="profile-title">CMND</li>
                <li>
                    <input type="text" class="form-control" id="add-manager-id" ng-model="AddManagerCtrl.manager_id" name="manager_id" autocomplete="off" spellcheck="false"/>
                </li>
                <li class="profile-title">Họ tên</li>
                <li>
                    <input type="text" class="form-control" id="add-manager-name" ng-model="AddManagerCtrl.manager_name" name="manager_name" autocomplete="off" spellcheck="false"/>
                </li>
                <li class="profile-title">Tên đăng nhập</li>
                <li>
                    <input type="text" class="form-control" id="add-manager-user" ng-model="AddManagerCtrl.manager_user" name="manager_user" autocomplete="off" spellcheck="false"/>
                </li>
                <li class="profile-title" ng-show="AddManagerCtrl.show">Hãng xe</li>
                <li>
                    <select class="combobox" name="manager_operator">
                        <?php foreach($operators as $operator) : ?>
                            <option value="<?php echo $operator['MaHangXe'] ?>"><?php echo $operator['TenHangXe'] ?></option>
                        <?php endforeach ?>
                    </select>
                </li>
                <li class="center profile-buttons">
                    <button type="button" class="btn btn-default" ng-click="AddManagerCtrl.back()">Trở về</button>
                    <button type="button" id="btn-submit" ng-click="AddManagerCtrl.submit()" class="btn btn-primary">Đồng ý</button>
                    <input type="hidden" name="is_add_manager" value="1"/>
                </li>
            </ul>
        </form>
    </div>
</div>

<div class="modal fade" id="add-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">Thông báo</h4>
            </div>
            <div class="modal-body">
                <h5 id="error-content"></h5>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">OK</button>
            </div>
        </div>
    </div>
</div>