<div class="main-contain" ng-controller="managementController as ManagementCtrl">
    <div class="contain center-screen" ng-controller="searchManagerController as searchCtrl">
        <div class="col-md-6">
            <h5>Từ khóa</h5>
            <input type="text" class="form-control" autocomplete="off" ng-model="searchCtrl.search_keyword" name="search_keyword"/>
        </div>
        <div class="col-md-3">
            <h5>Tiêu chí</h5>
            <div class="dropdown">
                <button class="btn btn-default dropdown-toggle" type="button" id="dropdown-search" data-toggle="dropdown">
                    Tìm kiếm
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dropdown-search">
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="javascript:void(0)" ng-click="searchCtrl.searchID()">CMND</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="javascript:void(0)" ng-click="searchCtrl.searchName()">Họ tên</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="javascript:void(0)" ng-click="searchCtrl.searchUser()">Tên đăng nhập</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="javascript:void(0)" ng-click="searchCtrl.searchOperator()">Hãng xe</a></li>
                </ul>
            </div>
        </div>
        <div class="col-md-3 buttons">
            <button type="button" class="btn btn-info" data-ng-click="ManagementCtrl.addManager()">
                <span class="glyphicon glyphicon-plus"></span>Thêm
            </button>
        </div>
    </div>
    <form action="/admin/manager/edit" method="post">
        <input type="hidden" name="manager_id" class="manager-id"/>
        <div class="table-responsive table-space">
            <table class="table table-bordered table-hover">
                <thead>
                <tr>
                    <th>CMND</th>
                    <th>Họ tên</th>
                    <th>Tên đăng nhập</th>
                    <th>Quản trị viên</th>
                    <th>Hãng xe</th>
                    <th class="col-function">#</th> <!-- Remove Column -->
                </tr>
                </thead>
                <tbody>
                <?php foreach ($managers as $manager) : ?>
                    <tr>
                        <td class="col-id">
                            <?php echo $manager['CMND'] ?>
                        </td>
                        <td class="col-name">
                            <?php echo $manager['HoTen'] ?>
                        </td>
                        <td class="col-username">
                            <?php echo $manager['TenDangNhap'] ?>
                        </td>
                        <td class="col-is-admin center">
                            <?php if ($manager['QuanTriVien'] == 1) : ?>
                                <span class="glyphicon glyphicon-ok green"></span>
                            <?php else : ?>
                                <span class="glyphicon glyphicon-remove red"></span>
                            <?php endif ?>
                        </td>
                        <td class="col-operator-name">
                            <?php echo $manager['TenHangXe'] ?>
                        </td>
                        <td>
                            <button type="button" class="btn btn-danger btn-function" data-toggle="modal" data-target="#remove-manager-modal">
                                <span class="glyphicon glyphicon-remove"></span>Xóa
                            </button>
                        </td>
                    </tr>
                <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </form>
    <nav class="center" ">
    <ul class="pagination">
        <li><a href="#">&laquo;</a></li>
        <li><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">5</a></li>
        <li><a href="#">&raquo;</a></li>
    </ul>
    </nav>
</div>

<div class="modal fade" id="remove-manager-modal" tabindex="-1" role="dialog" aria-labelledby="modal-title" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <form action="/admin/manager/delete" method="post">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="modal-title">Thông báo</h4>
                </div>
                <div class="modal-body">
                    Bạn có chắc chắn muốn xóa chứ?
                </div>
                <div class="modal-footer">
                    <input type="hidden" name="manager_id" class="manager-id"/>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Thoát</button>
                    <button type="submit" class="btn btn-primary">Đồng ý</button>
                </div>
            </form>
        </div>
    </div>
</div>