<div class="main-contain" ng-controller="addOperatorController as AddOperatorCtrl">
    <div class="sub-contain center-screen">
        <form action="/admin/operator/add" id="add-operator-form" enctype="multipart/form-data" method="post">
            <ul>
                <li class="sub-contain-title">Tên hãng xe</li>
                <li>
                    <input type="text" id="add-operator-name" class="form-control" name="operator_name" ng-model="AddOperatorCtrl.operator_name" autocomplete="off"/>
                </li>
                <li class="sub-contain-title">Logo</li>
                <li id="file-logo">
                    <div>
                        <input id="input-id" type="file" class="file" data-show-upload="false" name="logo" data-preview-file-type="text" >
                    </div>
                </li>
                <li class="sub-contain-button">
                    <button type="button" class="btn btn-default" ng-click="AddOperatorCtrl.back()">Trở về</button>
                    <button type="button" id="btn-submit" class="btn btn-primary" ng-click="AddOperatorCtrl.submit()">Hoàn tất</button>
                    <input type="hidden" name="is_add_operator" value="1"/>
                </li>
            </ul>
        </form>
    </div>
</div>

<div class="modal fade" id="add-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">Thông báo</h4>
            </div>
            <div class="modal-body">
                <h5 id="error-content"></h5>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">OK</button>
            </div>
        </div>
    </div>
</div>