<div class="main-contain" ng-controller="regulationController as RegulationCtrl">
    <div class="contain center-screen" ng-controller="searchRegulationController as searchCtrl">
        <div class="col-md-6">
            <h5>Từ khóa</h5>
            <input type="text" class="form-control" autocomplete="off" ng-model="searchCtrl.search_keyword" name="search_keyword"/>
        </div>
        <div class="col-md-3">
            <h5>Tiêu chí</h5>
            <div class="dropdown">
                <button class="btn btn-default dropdown-toggle" type="button" id="dropdown-search" data-toggle="dropdown">
                    Tìm kiếm
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dropdown-search">
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="javascript:void(0)" ng-click="searchCtrl.searchDateFrom()">Ngày bắt đầu</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="javascript:void(0)" ng-click="searchCtrl.searchDateTo()">Ngày kết thúc</a></li>
                </ul>
            </div>
        </div>
        <div class="col-md-3 buttons">
            <button type="button" class="btn btn-info" ng-click="RegulationCtrl.addRegulation()">
                <span class="glyphicon glyphicon-plus"></span>Thêm
            </button>
        </div>
    </div>
    <form action="/admin/regulation/edit" method="post">
        <input type="hidden" name="regulation_id" class="regulation-id"/>
        <div class="table-responsive table-space">
            <table class="table table-bordered table-hover">
                <thead>
                <tr>
                    <th>Mã điều tiết</th>
                    <th>Ngày bắt đầu</th>
                    <th>Ngày kết thúc</th>
                    <th>Phần trăm</th>
                    <th>Lý do</th>
                    <th class="col-function">#</th> <!-- Edit Column -->
                    <th class="col-function">#</th> <!-- Remove Column -->
                </tr>
                </thead>
                <tbody>
                <?php foreach ($regulations as $regulation) : ?>
                    <tr>
                        <td class="col-id">
                            <?php echo $regulation['MaDT'] ?>
                        </td>
                        <td class="col-name">
                            <?php echo $regulation['NgayBatDau']->format('d/m/Y') ?>
                        </td>
                        <td class="col-name">
                            <?php echo $regulation['NgayKetThuc']->format('d/m/Y') ?>
                        </td>
                        <td class="col-name">
                            <?php echo $regulation['PhanTram'] ?>
                        </td>
                        <td class="col-name">
                            <?php echo $regulation['LyDo'] ?>
                        </td>
                        <td>
                            <button type="submit" class="btn btn-warning btn-function">
                                <span class="glyphicon glyphicon-edit"></span>Sửa
                            </button>
                        </td>
                        <td>
                            <button type="button" class="btn btn-danger btn-function" data-toggle="modal" data-target="#remove-regulation-modal">
                                <span class="glyphicon glyphicon-remove"></span>Xóa
                            </button>
                        </td>
                    </tr>
                <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </form>
    <nav class="center" ">
    <ul class="pagination">
        <li><a href="#">&laquo;</a></li>
        <li><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">5</a></li>
        <li><a href="#">&raquo;</a></li>
    </ul>
    </nav>
</div>

<div class="modal fade" id="remove-regulation-modal" tabindex="-1" role="dialog" aria-labelledby="modal-title" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <form action="/admin/regulation/delete" method="post">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="modal-title">Thông báo</h4>
                </div>
                <div class="modal-body">
                    Bạn có chắc chắn muốn xóa chứ?
                </div>
                <div class="modal-footer">
                    <input type="hidden" name="regulation_id" class="regulation-id"/>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Thoát</button>
                    <button type="submit" class="btn btn-primary">Đồng ý</button>
                </div>
            </form>
        </div>
    </div>
</div>